//Script finds the image based on pitcure ID and displays it along with a download button in the claimPage
    // Script by: Javier Gonzalez javier.e.glz@gmail.com


function displayPictureModal(){
    document.getElementById("reportIssueModal").style.display = "none";
    document.getElementById("claimPhotoModal").style.display = "block";
    let pictureID = document.getElementById("picID").value;
    setPicture(pictureID);
  };

function setPicture(pictureID){
  let imgPath = `https://res.cloudinary.com/memorycaptures-com/image/upload/MemoriesCaptured/IMG_${pictureID}.jpg`;
  let imgReduced = `https://res.cloudinary.com/memorycaptures-com/image/upload/c_limit,h_800,w_800/MemoriesCaptured/IMG_${pictureID}.jpg`;

  let displayPhotoHTML = `<a id="downloadLink" 
                          class="buttonStyle" 
                          href=${imgPath} 
                          download="Captured Memory.jpg" 
                          target="blank">

                            DOWNLOAD LINK

                          </a> <br>
                          
                          <a id="imglink" 
                          href=${imgPath} 
                          target="blank">

                              <img src =${imgReduced} 
                              class="previewImg"
                              alt="Captured Memory" 
                              title="View Full Resolution Image">
                              
                          </a>`

  let displayErrorHTML = `<h4>Sorry, it seems the code you entered is incorrect. </h4>
                          <h4>Please double check the code or contact us to get your photo.</h4><br>`

  let loadingScreenHTML =`<div class="lds-ellipsis"><div></div><div></div><div></div><div></div></div>
                          <h3>Loading...</h3>
                          <h4>Contact Us for Booking Private Events</h4><br>`


  renderContentsModal(pictureID, loadingScreenHTML, imgPath, displayPhotoHTML, displayErrorHTML);
};

function renderContentsModal(pictureID, loadingScreenHTML, imgPath, displayPhotoHTML, displayErrorHTML) {
  if (pictureID == "") {
    document.getElementById("claimModalTitle").innerText = "Insert Your Photo Code";
    document.getElementsByClassName("claimPhoto")[0].innerHTML = "<h4>Please type in the code that was given to you at the time of your purchase</h4>";
  }
  else {
    document.getElementById("claimModalTitle").innerText = "Looking For Your Memory";
    document.getElementsByClassName("claimPhoto")[0].innerHTML = loadingScreenHTML;
    //Totally just setting a timer because it looks nice to have a loader
    setTimeout(function () {
      getPicture(imgPath, displayPhotoHTML, displayErrorHTML);
    }, 1500);
  }
}

function getPicture(url, displayHtml, errorHtml){
  //Aynchronous request to get the piture from url generated by pictureID
  let xhr = new XMLHttpRequest();
  xhr.open('GET', url, true);
  xhr.onreadystatechange = function(){
    if(this.readyState == 4){
        if(this.status == 200){
            console.log("Success: Image Code valid");
            document.getElementById("claimModalTitle").innerText = "Found Your Memory!";
            document.getElementsByClassName("claimPhoto")[0].innerHTML = displayHtml;
        }else{
            console.log("Error: Image Code Invalid");
            document.getElementById("claimModalTitle").innerText = "Picture Not Found";
            document.getElementsByClassName("claimPhoto")[0].innerHTML = errorHtml;
            }
    };};
  xhr.send();
};


function showReportIssueScreen(){
  document.getElementById("claimPhotoModal").style.display = "none";
  document.getElementById("reportIssueModal").style.display = "block";
  };

let showIssueForm = document.getElementById("reportIssueButton");
showIssueForm.addEventListener("click", function(){
  showReportIssueScreen()
}, false);
